name: Test Build

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: website/package-lock.json
        
    - name: Check file structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Files in website directory:"
        ls -la website/
        echo "Files in website/src directory:"
        ls -la website/src/
        echo "index.html content:"
        cat website/index.html
        
    - name: Install dependencies
      working-directory: ./website
      run: npm ci
      
    - name: Build website
      working-directory: ./website
      run: npm run build
      
    - name: List files
      working-directory: ./website
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Files in parent directory:"
        ls -la ..
        echo "Files in root:"
        ls -la ../..
